name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '0 2 * * 1'  # Run every Monday at 2 AM UTC

jobs:
  quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
          - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle
        
    - name: Validate Gradle
      run: ./gradlew validate
      
    - name: Check dependencies
      run: ./gradlew dependencies
      
    - name: Check for outdated dependencies
      run: ./gradlew dependencyUpdates
      
    - name: Validate code style
      run: ./gradlew checkstyle
      
    - name: Generate dependency tree
      run: ./gradlew dependencies > dependency-tree.txt
      
    - name: Upload dependency tree
      uses: actions/upload-artifact@v4
      with:
        name: dependency-tree
        path: dependency-tree.txt
        retention-days: 30
